
ALTER TABLE Sys_ErrLogInfo ALTER COLUMN ErrType NVARCHAR(MAX) NULL
GO
ALTER TABLE Sys_ErrLogInfo ALTER COLUMN UserName NVARCHAR(500) NULL
GO
ALTER TABLE Sys_ErrLogInfo ALTER COLUMN ErrUrl NVARCHAR(MAX) NULL
GO

ALTER TABLE EduTrain_TrainRecord ALTER COLUMN TrainContent NVARCHAR(MAX) NULL
GO
ALTER TABLE EduTrain_TrainRecord ALTER COLUMN Remark NVARCHAR(MAX) NULL
GO