/****** Object:  Index [NonClusteredIndex-20210427-121713]    Script Date: 2021/4/27 12:23:52 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210427-121713] ON [dbo].[Sys_FlowOperate]
(
	[OperaterId] ASC,
	[IsClosed] ASC,
	[State] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


