--µ¥Î»×Ö¶ÎÐÞ¸Ä
ALTER TABLE Base_Unit ALTER COLUMN UnitCode NVARCHAR(100) NULL
GO
ALTER TABLE Base_Unit ALTER COLUMN UnitName NVARCHAR(200) NULL
GO
ALTER TABLE Base_Unit ALTER COLUMN Corporate NVARCHAR(100) NULL
GO
ALTER TABLE Base_Unit ALTER COLUMN Address NVARCHAR(500) NULL
GO
